name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  current_date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say date
        run: |
          date

  ls_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say current directory contents (ls)
        run: |
          ls