name: Scheduled Health Check

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2
        with:
          url: https://fso-pokedex-prb01.herokuapp.com/
          max-attempts: 3
          retry-delay: 5s
      - name: Discord | Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          text: 'Healthcheck successfull'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord | Error
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          text: 'Healthcheck issue'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
